name: Autograding Tests
'on': [push]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'adopt'
    - name: Test student code
      id: test-student-code
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test student code
        setup-command: chmod +x mvnw
        command: "./mvnw test"
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-STUDENT-CODE_RESULTS: "${{steps.test-student-code.outputs.result}}"
      with:
        runners: test-student-code